networks:
  backend:
    driver: bridge

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    image: sleep-diary-app-image
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend
    env_file:
      - .env
    environment:
      PRIVATE_KEY: ${PRIVATE_KEY:?}
      PUBLIC_KEY: ${PUBLIC_KEY:?}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "8000:8000"
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    entrypoint:
      - uvicorn
      - --factory
      - src.application.api.main:create_app
      - --host=0.0.0.0
      - --port=8000
      - --reload