version: "3.8"
services:
  sleep_diary:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sleep_diary
    image: sleep_diary:0.1
    ports:
      - "5000:5000"
    env_file:
      - .env