version: "3.8"
networks:
  my_net:
volumes:
  db:
    driver: local
services:
  sleep_diary:
    build:
      context: .
      dockerfile: Dockerfile
    image: sleep_diary:0.1
    restart: always
    networks:
      - my_net
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DB_DRIVER: postgresql
      DB_EXTEND_DRIVER: psycopg2
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: postgres
    volumes:
      - ./app:/sleep_diary/app
#      - ./test.db:/sleep_diary/test.db
    command: python run.py
#    command: ls -la

  postgres:
    image: postgres:16
    restart: always
    networks:
      - my_net
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8.4
    restart: always
    networks:
      - my_net
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin





