version: "3.8"
services:
  sleep_diary:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sleep_diary
    image: sleep_diary:0.1
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./app:/sleep_diary/app
#      - ./test.db:/sleep_diary/test.db
    links:
      - db
#    depends_on:
#      db:
#        condition: service_completed_successfully
    command: python run.py
#    command: ls -la

  db:
    container_name: db_postgres
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always
#    volumes:
#      - db:/var/lib/postgresql/data
#      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3
#volumes:
#  db:
#    driver: local

