services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: sleep-diary-app-image
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    env_file:
      - .env
    environment:
      SECRET_KEY: ${SECRET_KEY:?}
      DB_DRIVER: ${DB_DRIVER:?}
      DB_DRIVER_EXTENSION: ${DB_DRIVER_EXTENSION:?}
      DB_USER: ${DB_USER:?}
      DB_PASSWORD: ${DB_PASSWORD:?}
      DB_HOST: ${DB_HOST:?}
      DB_PORT: ${DB_PORT:?}
      DB_NAME: ${DB_NAME:?}
      PRIVATE_KEY: ${PRIVATE_KEY:?}
      PUBLIC_KEY: ${PUBLIC_KEY:?}
    ports:
      - "8000:8000"
    networks:
      - backend
    working_dir: /app
    entrypoint:
      - flask
      - --app=src.flask_app:create_app
      - run
      - --reload
      - --host=0.0.0.0
      - --port=8000

  postgres:
    image: postgres:16
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
      POSTGRES_DB: ${POSTGRES_DB:?}
    ports:
      - "54321:5432"
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4:8.4
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:?}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:?}
    ports:
      - "5050:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge
