services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: sleep-diary-app-image
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    env_file:
      - .env
    environment:
      SECRET_KEY: ${SECRET_KEY:?}
      POSTGRES_DB: ${POSTGRES_DB:?}
      POSTGRES_USER: ${POSTGRES_USER:?}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?}
      POSTGRES_HOST: ${POSTGRES_HOST:?}
      POSTGRES_PORT: ${POSTGRES_PORT:?}
      PRIVATE_KEY: ${PRIVATE_KEY:?}
      PUBLIC_KEY: ${PUBLIC_KEY:?}
    ports:
      - "8000:8000"
    networks:
      - backend
    working_dir: /app
    entrypoint:
      - flask
      - --debug
      - --app=src.application.app:init_app
#      - --app=src.flask_app:create_app
      - run
      - --reload
      - --host=0.0.0.0
      - --port=8000

networks:
  backend:
    driver: bridge
