services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: sleep-diary-app-image
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    env_file:
      - .env
    environment:
      SECRET_KEY: ${SECRET_KEY:?}
      DB_DRIVER: ${DB_DRIVER:?}
      DB_DRIVER_EXTENSION: ${DB_DRIVER_EXTENSION:?}
      DB_USER: ${DB_USER:?}
      DB_PASSWORD: ${DB_PASSWORD:?}
      DB_HOST: ${DB_HOST:?}
      DB_PORT: ${DB_PORT:?}
      DB_NAME: ${DB_NAME:?}
      PRIVATE_KEY: ${PRIVATE_KEY:?}
      PUBLIC_KEY: ${PUBLIC_KEY:?}
    ports:
      - "8000:8000"
    networks:
      - backend
    working_dir: /app
    entrypoint:
      - flask
      - --app=src.flask_app:create_app
      - run
      - --reload
      - --host=0.0.0.0
      - --port=8000

networks:
  backend:
    driver: bridge
