[tool.black]
line-length = 85
target-version = ["py310"]

[tool.poetry]
name = "sleep-diary-app"
version = "0.1.0"
description = ""
authors = ["ivan"]
license = "MIT License"
readme = "README.md"
package-mode = false


[tool.poetry.dependencies]
python = "^3.10"
flask = "^3.0.3"
flask-sqlalchemy = "^3.1.1"
pydantic = "^2.7.4"
bcrypt = "^4.1.3"
flask-restx = "^1.3.0"
pydantic-settings = "^2.3.3"
pyjwt = { extras = ["crypto"], version = "^2.8.0" }
more-itertools = "^10.3.0"
jsonref = "^1.1.0"
psycopg2-binary = "^2.9.9"


[tool.poetry.group.dev.dependencies]
pytest-html = "^4.1.1"
faker = "^25.9.1"
pytest-dotenv = "^0.5.2"
pytest-cov = "^5.0.0"
pytest-repeat = "^0.9.3"
pytest-xdist = "^3.6.1"
pytest-metadata = "^3.1.1"
pytest = "^8.2.2"
black = "^24.4.2"
coverage = "^7.5.3"
mypy = "^1.10.0"

[tool.poetry.scripts]
app = "flask --app=src.flask_app:create_app run --reload --host=0.0.0.0 --port=8000"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
