name: Run tests

on:
  push:
    branches: [master, development, gh_actions]
  pull_request:
    branches: [master, development]


jobs:
  build-sleep-diary-app-image:
    name: Сборка образа Sleep Diary Python приложения
    runs-on: ubuntu-22.04
    services:
      postgres:
        container_name: postgres
        image: postgres:16
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Сборка
        run: |
          make build
      - name: Сборка
        run: |
          docker images

#  run-unit-tests:
#    name: Прогон unit тестов
#    runs-on: ubuntu-22.04
#    needs: [build-sleep-diary-app-image]
#    steps:
#        uses: pytest tests/unit
#
#  run-integration-tests:
#    name: Прогон integration тестов
#    runs-on: ubuntu-22.04
#    needs: [build-sleep-diary-app-image]
#    steps:
#      uses: pytest tests/integration
#
#  run-e2e-tests:
#    name: Прогон e2e тестов
#    runs-on: ubuntu-22.04
#    needs: [up-postgresql-server, build-sleep-diary-app-image]
#    steps:
#      uses: pytest tests/e2e





