name: Run tests

on:
  push:
    branches: [master, development]
  pull_request:
    branches: [master, development]

jobs:
  run-tests:
    name: Прогон тестов в контейнере
    runs-on: ubuntu-22.04
    env:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Запуск PostgreSQL сервера в контейнере
        run: make up-postgres

      - name: Сборка образа Sleep Diary из Dockerfile
        run: make build

      - name: Запуск unit тестов
        run: make unit

      - name: Запуск integration тестов
        run: make integration

      - name: Запуск e2e тестов
        run: make e2e

      - name: Запусков всех тестов
        run: make all

      - name: Остановка контейнера с сервером PostgreSQL
        if: always()
        run: make down-postgres
